#!/usr/bin/env bash

set -euo pipefail

print_help() {
    echo "Installs latest version of deps.clj. Installation directory defaults to /usr/local/bin."
    echo -e
    echo "Usage:"
    echo "installer.sh [<dir>]"
    exit 1
}

default_install_dir="/usr/local/bin"
install_dir=$default_install_dir
install_dir_opt=${1:-}
if [ "$install_dir_opt" ]; then
    install_dir="$install_dir_opt"
fi

download_dir=/tmp

latest_release="$(curl -sL https://raw.githubusercontent.com/borkdude/deps.clj/master/resources/DEPS_CLJ_RELEASED_VERSION)"

case "$(uname -s)" in
    Linux*)     platform=linux;;
    Darwin*)    platform=macos;;
esac

download_url="https://github.com/borkdude/deps.clj/releases/download/v$latest_release/deps.clj-$latest_release-$platform-amd64.zip"

cd "$download_dir"
echo -e "Downloading $download_url."
curl -o "deps.clj-$latest_release-$platform-amd64.zip" -sL "https://github.com/borkdude/deps.clj/releases/download/v$latest_release/deps.clj-$latest_release-$platform-amd64.zip"
unzip -qqo "deps.clj-$latest_release-$platform-amd64.zip"
rm "deps.clj-$latest_release-$platform-amd64.zip"

cd "$install_dir"
if [ -f deps.exe ]; then
    echo "Moving $install_dir/deps.exe to $install_dir/deps.exe.old"
fi

mv -f "$download_dir/deps.exe" "$PWD/deps.exe"

echo "Successfully installed deps.exe in $install_dir."
