#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp deps /tmp/release

VERSION=$(cat resources/DEPS_CLJ_VERSION)

pushd /tmp/release

## release binary as zip archive

artifact="deps.clj-$VERSION-$DEPS_CLJ_PLATFORM-amd64.zip"
zip "$artifact" deps

popd

bb upload-artifact :file "/tmp/release/$artifact"

rm deps
