#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp deps /tmp/release

VERSION=$(cat resources/DEPS_CLJ_VERSION)

cd /tmp/release

## release binary as zip archive

zip "deps.clj-$VERSION-$DEPS_CLJ_PLATFORM-amd64.zip" deps

rm deps
