#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true

DEPS_CLJ_VERSION=$(cat resources/DEPS_CLJ_VERSION)

lein deps.clj -Spath -Sdeps '{:deps {borkdude/deps.clj {:mvn/version "0.0.1"}}}'

lein with-profiles +native-image do clean, uberjar

"$GRAALVM_HOME/bin/native-image" \
  -jar target/deps.clj-$DEPS_CLJ_VERSION-standalone.jar \
  -H:Name=deps.exe \
  -H:+ReportExceptionStackTraces \
  -J-Dclojure.spec.skip-macros=true \
  -J-Dclojure.compiler.direct-linking=true \
  "-H:IncludeResources=DEPS_CLJ_VERSION" \
  --initialize-at-build-time \
  -H:Log=registerResource: \
  --verbose \
  --no-fallback \
  "-H:EnableURLProtocols=http,https" \
  "--enable-all-security-services" \
  --no-server \
  "-J-Xmx3g"

lein clean

./deps.exe -Spath -Sdeps '{:deps {borkdude/deps.clj {:mvn/version "0.0.1"}}}'
